### ISSUE TITLE
切换controller时view上跳

### ISSUE THREAD

**Issue by nlpjoe** [yuping1989/YPTabBarController#1]
喻平大哥你好，我用你的代码在切换controller的时候view会上跳，需要点击一下屏幕才会恢复，这个bug很不爽，看了你的源码也不知道错在哪里，我有navigationbar和tabbar，你觉得可能的问题是什么？

**Comment by yuping1989** [comment]
你好，谢谢你提的问题哈！我今天看一下怎么回事，先确认一下，你是把TabBarController作为NavigationController的rootController这样吗？

**Comment by su350380433** [comment]
是这样啊，会上下跳到怎么处理呢

**Comment by yuping1989** [comment]
可不可以给我看看你的相关代码呢？

**Comment by BiggerGao** [comment]
我的代码你可能跑不起来，我估计是navigation bar的原因，不过我昨天看了下你的代码，点击title 的scrollview没有移动噢

**Comment by qyzhaojinxi** [comment]
@BiggerGao 请问这个问题解决了么

**Comment by yuping1989** [comment]
兄弟，问题已经解决了哈，更新最新的版本即可

**Comment by qyzhaojinxi** [comment]
ok，已解决
