### ISSUE TITLE
快速滑动会造成崩溃

### ISSUE THREAD

**Issue by HaiFengWei** [yuping1989/YPTabBarController#13]
当我快速滑动的时候，程序崩了，报Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIScrollViewPagingSwipeGestureRecognizer translationInView:]: unrecognized selector sent to instance 0x6080001d9500'。用demo跑的

**Comment by yuping1989** [comment]
好的，我下个版本修复这个问题

**Comment by yuping1989** [comment]
谢谢你的反馈！

**Comment by yuping1989** [comment]
你好，这个问题已经修复了哈
