### ISSUE TITLE
关于YPTabBarDelegate 的方法

### ISSUE THREAD

**Issue by wangbiye** [yuping1989/YPTabBarController#17]
我新建一个 ViewController 继承于 YPTabBarController, 然后遵守YPTabBarDelegate协议, 并且实现了didSelectedItemAtIndex的方法, 但是再 YPTabBarController 中该方法已经被实现过了, 在我自己的 Controller 中就要调用[super yp_tabBar:tabBar didSelectedItemAtIndex:index] 才可以, 要不然页面显示就会不正确, 这个写法总感觉怪怪的, 望解惑

**Comment by yuping1989** [comment]
你可以在你的子类里面实现这个方法，didSelectViewControllerAtIndex
