### ISSUE TITLE
请问如何修改底部tabbarItem的文字颜色？

### ISSUE THREAD

**Issue by jincheng555** [yuping1989/YPTabBarController#19]
请问如何修改底部tabbarItem的文字颜色？

**Comment by yuping1989** [comment]
YPTabBar的这两个属性：
@property (nonatomic, strong) UIColor *itemTitleColor;              // 标题颜色
@property (nonatomic, strong) UIColor *itemTitleSelectedColor;      // 选中时标题的颜色

**Comment by jincheng555** [comment]
谢谢解答，问题已解决。改错地方了，改成顶部title的颜色了~
