### ISSUE TITLE
iOS11，iPhoneX适配问题

### ISSUE THREAD

**Issue by nqwl** [yuping1989/YPTabBarController#25]
没有适配iOS11出现问题较多。

**Comment by twisturn** [comment]
同问

**Comment by yuping1989** [comment]
请问具体是什么问题，我用iPhone8的模拟器跑demo没发现问题，iPhone X的话，通过setTabBarFrame方法可以解决

**Comment by twisturn** [comment]
@yuping1989 之前的问题已经解决，但是很高兴收到你的回复，谢谢。
