### ISSUE TITLE
YPTabItem文字错位

### ISSUE THREAD

**Issue by qyzhaojinxi** [yuping1989/YPTabBarController#3]
你好，我遇到个问题，在ios10上，YPTabItem上的文字跑到了图片右边，点击几次后恢复正常，这个是怎么回事呢？

**Comment by yuping1989** [comment]
抱歉，还没有对iOS10进行适配哈

**Comment by qyzhaojinxi** [comment]
恩，希望能尽快，毕竟就剩两个月了

**Comment by qyzhaojinxi** [comment]
你好，因为我现在项目中用的你这个类库，可能会经常有问题请教。除了这个问题以外，我还有个问题，我现在页面结构是这样的rootController（YPTabBarController）->nav->顶部tab控制器(YPTabBarController)->Viewcontroller(里边是tableview列表)，因为要实现push，所以在顶部tab外层嵌套了这个nav，这个也算是很常见的结构了。但是在使用水平滑动切换tab时，viewcontroller里的view会很不正常的向下偏移，然后回去，而且下拉刷新的控件也不知道被什么遮住了，看不到。感觉就像是scrollview的contensize的height计算有问题，导致Viewcontroller里的tableview垂直方向滚动和外边的scrollview互相冲突了。你能帮忙看下是怎么回事么？或者提供一个有导航控制器的demo
