### ISSUE TITLE
Hook ScrollView的代理方法影响到了WKWebView的滚动刷新

### ISSUE THREAD

**Issue by liuxiaoxinxin** [yuping1989/YPTabBarController#49]
嗨，喻平，在新版本里我看到你hook了UIScrollView的Delegate方法，而这个会影响到WKWebView的滚动刷新，导致网页滚动后刷新不及时而白屏。
一种可能的解决方式是使用KVO去捕获ScrollView滚动。

**Comment by yuping1989** [comment]
额，为什么关闭了？

**Comment by liuxiaoxinxin** [comment]
> 额，为什么关闭了？

手抖多点了次提交了2个issues，所以关了一个。

**Comment by yuping1989** [comment]
好的。
用KVO捕获ScrollView滚动这种方式无法满足需求，但是hook代理的方式也确实可能产生一些问题，没办法只能通过额外暴露接口的方式了，我会去掉对代理的hook，估计要花3天左右时间

**Comment by yuping1989** [comment]
你好，我能加你一个qq吗？了解一下具体问题

**Comment by yuping1989** [comment]
兄弟，你试试在你WKWebView所在的View Controller中加入这个方法，应该能解决你的问题

- (UIScrollView *)yp_scrollView {
    return self.wkWebView.scrollView;
}

**Comment by liuxiaoxinxin** [comment]
抱歉最近忙着赶需求没注意到回复，我的 QQ： 969068127
