### ISSUE TITLE
会不会有内存泄漏啊？

### ISSUE THREAD

**Issue by wangjuanlsx** [yuping1989/YPTabBarController#5]
我那xcode的带的检测工具检测。。。发现内存泄漏哎。。。求楼主解答下。。。我对这方面也不是很懂。。。所以还是来问问你。。。求解答。。

**Comment by yuping1989** [comment]
这个我看一下，有结果了回复你

**Comment by yuping1989** [comment]
兄弟，我用Instruments检测了一下，没有内存泄露呀。这个没有用到C语言接口，所以不会存在没有释放内存的问题。

**Comment by qyzhaojinxi** [comment]
我觉得这哥们可能只是用静态分析检测了下
