### ISSUE TITLE
喻平大哥，江湖救急

### ISSUE THREAD

**Issue by songliguo** [yuping1989/YPTabBarController#7]
喻平大哥你好，我用你的代码集成在了项目中，但是想实现手动切换tabbar选项卡，只用做了项目的tabbar控制器，喻平大哥可以添加一个changeTabBarItem fromIndex  ToIndex 的方法吗？  我尝试着改了一下您的代码，但是效果并不好，或者有方式实现，小弟不才，没有找到。麻烦您可以指导一下吗？

**Comment by songliguo** [comment]
喻平大哥，急需。。。

**Comment by yuping1989** [comment]
抱歉今天才看到你的问题。
手动切换tab bar是有办法实现的，YPTabBar里面有个selectedItemIndex属性，你设置它就能实现手动切换tab，并且会出发它的didSelectedItemAtIndex代理，你可以实现它做一些你自己的页面切换操作
