### ISSUE TITLE
不能默认选中第二个或者第三个item嘛

### ISSUE THREAD

**Issue by gujianhui** [yuping1989/YPTabBarController#9]
不能默认选中第二个或者第三个item嘛  
@property (nonatomic, assign) NSInteger selectedItemIndex;          // 选中某一个item
这个属性不是设置默认选中某个item嘛   尝试这个属性之后是可以设置默认的item 但是为什么设置这个属性不起作用 但是用延迟执行的方法的时候却管用呢

**Comment by yuping1989** [comment]
但是这句代码要在viewWillAppear里面写，因为父类的初始化默认选中item是在viewWillAppear里写的

**Comment by gujianhui** [comment]
嗯嗯 好的 谢谢
